// <auto-generated />
namespace MotorcycleCommunityProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _5thAttempt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5thAttempt));
        
        string IMigrationMetadata.Id
        {
            get { return "202102190114489_5thAttempt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
